mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.70.180.28:3300/sourcemod-local?useUnicode=true&characterEncoding=utf-8
    username: root
    password: MtC123456mysql
    hikari:
      max-lifetime: 30000

jwt:
  header: Authorization
  secret: Bone
  expiration: 36000