server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://124.70.180.28:3300/sourcemod-local?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
#    url: jdbc:mysql://127.0.0.1:3306/c5?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: MtC123456mysql
#    password: root
    hikari:
      max-lifetime: 30000
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL57Dialect